version: "3"
services:
    app:
        build:
            context: .
            dockerfile: docker/app.Dockerfile
        image: app-gateway
        ports:
            - "5000:5000"
        networks:
            - net-gateway
        links:
            - db:db
        depends_on:
            - db
        environment:
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "postgres"
            DB_PWD: "postgres"
            DB_NAME: "gateway"
            DB_TYPE: "postgres"

    db:
        build:
            context: .
            dockerfile: docker/db.Dockerfile
        image: postgres-gateway
        ports:
            - "5432:5432"
        networks:
            - net-gateway
        environment:
            POSTGRES_USER: "postgres"
            DB_NAME: "gateway"

networks:
    net-gateway:
        driver: bridge